### ISSUE TITLE
Tag management in digital hub

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#140]
### DESC
- differentiate between the tags like "technical" / "content based" tags+
- think about: handling in two different collections VS one collections with additional metadata fields
- singular components (tags are lower lvl / on technical lvl) AND apps (different categories / like gamification / )
- official reinherit toolkit app (as tag)

#### Webinars
- links to tools hub
- upload stuff on zenodo and link to it on the hub / 
- link google scholar / zotero / on metadata lvl? 
- way to attract people to the digital hub
- news / events on webinars / update to specific 

### TODOs
- [x] wait for chiara's tag list
- [x] implement

**Comment by kia-z** [comment]
solved in May workshop and June discussions
