### ISSUE TITLE
Integrate clickmeeting

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#220]
### DESC
- test out integration of clickmeeting of the page
- https://v3.gatsbyjs.com/docs/reference/config-files/gatsby-ssr/#onRenderBody
- https://stackoverflow.com/questions/60052078/how-to-add-external-javascript-in-gatsby
- https://stackoverflow.com/questions/60714611/how-do-i-include-embed-code-with-an-external-script-in-the-body-of-a-gatsby-site
- https://www.gatsbyjs.com/docs/using-client-side-only-packages/

### TODOs
- [x] easy to embed -> no / because of rendering mechanism from gatsby. 🔴 
- [x] workaround

**Comment by kia-z** [comment]
tested, discussed, and solved
