### ISSUE TITLE
Hub-Refinement: Structural Changes 

### ISSUE THREAD

**Issue by krottmas** [ReInHerit/digital-hub#238]
- [x] Move the "portal buttons" of each subpage (= Resources, Networking, 'Content') to a dropdown menu (named Portals (??) or Area (??) next to the search
- [x] Social media Buttons, search Button and CMS access button next to the "Portal Buttons" can also go (away mainly :D, i think it is enough having those in the footer) 
- [x] The Breadcrumb in the About section works kinda funky -> either not continuing or not working at all 
- [x] Imprint and Data protection in About section to organize in cards
- [x] "Coming soon" pages need a working breadcrumb :) 
- [x] #248
- [x] In  https://reinherit-hub.eu/cms/ the "detailed manual" link needs the right link --> https://reinherit-hub.eu/doc/howto
- [x] Add Download Button to e-shop Items

**Comment by Stoff-Sebi** [comment]
implemented
