### ISSUE TITLE
Active link with gatsby

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#70]
### DESC
- problematic because also need to account for the mode? 
- think about: is the mode still necessary?
- https://www.evandromacedo.com/active-nav-links-in-many-routes-with-gatsby-and-styled-components/

### TODOs
- [ ] create wrapper for Gatsby link
- [ ] use own created link wrapper component

**Comment by Stoff-Sebi** [comment]
completely removed mode based workflow
